
<?php 

$con = mysqli_connect('localhost','root','','spingharkabuledu_laravel_api');

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/v15.0/922127214530498?fields=posts%7Bfull_picture%2Cid%2Cmessage%2Ccreated_time%7D%2Cname%2Cpicture&access_token=EAAJIwCcdItMBAPwCwlKPwQebwyJZBIqouiLuLOS5aZCXWRLyKqKzeAzIapGZBsU3wKHQVaX3q5ZCUA0vF5sXSaj5H2jtkKn9bLy6zKNHwaNO559ATZALIG3MBuz3mHCd38wCEA23kGurUnpZBqDF4HyC8hKVf6BN268BVO4ZCFBAQ75PdXmE9i5');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);


$result = json_decode($result);

//bigint = 9,223,372,036,854,775,807
//If id column value greater than 100,000,000,000 drop table and create it again


 $sql = "SELECT id FROM facebook_page_post WHERE id > 100";
$re = mysqli_query($con, $sql);

if (mysqli_num_rows($re) > 0) {

} else {
  mysqli_query($con, "drop table IF EXISTS facebook_page_post");
  mysqli_query($con, "create table facebook_page_post(
id bigint primary key auto_increment,
post_id varchar(255) null,
message text null,
full_picture text null,
created_time varchar(255) null,
page_name varchar(255) null,
page_picture text null);");
}




 mysqli_query($con, "delete from facebook_page_post");


foreach ($result->posts->data as $list) {
    $message = '';
    $post_id = '';
    $full_picture = '';
    $created_time = '';
    $page_name = '';
    $page_picture = '';

    if (isset($list->message)) {
        $message = $list->message;
    }

    if (isset($list->full_picture)) {
        $full_picture = $list->full_picture;
    }

     if (isset($list->id)) {
        $post_id = $list->id;
    }

        
        $created_time = $list->created_time;
        $page_name = $result->name;
        $page_picture = $result->picture->data->url;

         mysqli_query($con, "insert into facebook_page_post (post_id,message, full_picture, created_time, page_name, page_picture) values('$post_id','$message','$full_picture','$created_time','$page_name','$page_picture')");
    
}




?>





@extends('home.layout')



<style type="text/css">
    .u-border-1, .u-separator-1:after, .u-text.u-border-1, a.u-button-style.u-border-1 {
    border-width: 0px;
    background-color: #28292a !important;
    color: #ffffff !important;
}


</style>



@section('content')
 

<!-- Start WOWSlider.com BODY section -->
<!-- <div id="wowslider-container1" style="z-index: 1 !important">
<div class="ws_images"><ul>
  

   @foreach($photo as $home)
      

      <li><img src="data1/images/{{$home->Photo}}" alt="" title="" id="wows1_2"/></li>

    @endforeach



  </ul></div>

<div class="ws_shadow"></div>
</div>  
<script type="text/javascript" src="engine1/wowslider.js"></script>
<script type="text/javascript" src="engine1/script.js"></script> -->
<!-- End WOWSlider.com BODY section -->



        <!-- #region Jssor Slider Begin -->
    <!-- Generator: Jssor Slider Composer -->
    <!-- Source: https://www.jssor.com/demos/full-width-slider.slider/=edit -->
    <script src="js/jssor.slider-28.1.0.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        window.jssor_1_slider_init = function() {

            var jssor_1_SlideoTransitions = [
              [{b:-1,d:1,ls:0.5},{b:0,d:1000,y:5,e:{y:6}}],
              [{b:-1,d:1,ls:0.5},{b:200,d:1000,y:25,e:{y:6}}],
              [{b:-1,d:1,ls:0.5},{b:400,d:1000,y:45,e:{y:6}}],
              [{b:-1,d:1,ls:0.5},{b:600,d:1000,y:65,e:{y:6}}],
              [{b:-1,d:1,ls:0.5},{b:800,d:1000,y:85,e:{y:6}}],
              [{b:-1,d:1,ls:0.5},{b:500,d:1000,y:195,e:{y:6}}],
              [{b:0,d:2000,y:30,e:{y:3}}],
              [{b:-1,d:1,rY:-15,tZ:100},{b:0,d:1500,y:30,o:1,e:{y:3}}],
              [{b:-1,d:1,rY:-15,tZ:-100},{b:0,d:1500,y:100,o:0.8,e:{y:3}}],
              [{b:500,d:1500,o:1}],
              [{b:0,d:1000,y:380,e:{y:6}}],
              [{b:300,d:1000,x:80,e:{x:6}}],
              [{b:300,d:1000,x:330,e:{x:6}}],
              [{b:-1,d:1,r:-110,sX:5,sY:5},{b:0,d:2000,o:1,r:-20,sX:1,sY:1,e:{o:6,r:6,sX:6,sY:6}}],
              [{b:0,d:600,x:150,o:0.5,e:{x:6}}],
              [{b:0,d:600,x:1140,o:0.6,e:{x:6}}],
              [{b:-1,d:1,sX:5,sY:5},{b:600,d:600,o:1,sX:1,sY:1,e:{sX:3,sY:3}}]
            ];

            var jssor_1_options = {
              $AutoPlay: 1,
              $LazyLoading: 1,
              $CaptionSliderOptions: {
                $Class: $JssorCaptionSlideo$,
                $Transitions: jssor_1_SlideoTransitions
              },
              $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
              },
              $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$,
                $SpacingX: 20,
                $SpacingY: 20
              }
            };

            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

            /*#region responsive code begin*/

            var MAX_WIDTH = 1600;

            function ScaleSlider() {
                var containerElement = jssor_1_slider.$Elmt.parentNode;
                var containerWidth = containerElement.clientWidth;

                if (containerWidth) {

                    var expectedWidth = Math.min(MAX_WIDTH || containerWidth, containerWidth);

                    jssor_1_slider.$ScaleWidth(expectedWidth);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }

            ScaleSlider();

            $Jssor$.$AddEvent(window, "load", ScaleSlider);
            $Jssor$.$AddEvent(window, "resize", ScaleSlider);
            $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
            /*#endregion responsive code end*/
        };
    </script>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300italic,regular,italic,700,700italic&subset=latin-ext,greek-ext,cyrillic-ext,greek,vietnamese,latin,cyrillic" rel="stylesheet" type="text/css" />
    <style>
        /* jssor slider loading skin spin css */
        .jssorl-009-spin img {
            animation-name: jssorl-009-spin;
            animation-duration: 1.6s;
            animation-iteration-count: infinite;
            animation-timing-function: linear;
        }

        @keyframes jssorl-009-spin {
            from {
                transform: rotate(0deg);
            }

            to {
                transform: rotate(360deg);
            }
        }


        /*jssor slider bullet skin 132 css*/
        .jssorb132 {position:absolute;}
        .jssorb132 .i {position:absolute;cursor:pointer;}
        .jssorb132 .i .b {fill:#fff;fill-opacity:0.8;stroke:#000;stroke-width:1600;stroke-miterlimit:10;stroke-opacity:0.7;}
        .jssorb132 .i:hover .b {fill:#000;fill-opacity:.7;stroke:#fff;stroke-width:2000;stroke-opacity:0.8;}
        .jssorb132 .iav .b {fill:#000;stroke:#fff;stroke-width:2400;fill-opacity:0.8;stroke-opacity:1;}
        .jssorb132 .i.idn {opacity:0.3;}

        .jssora051 {display:block;position:absolute;cursor:pointer;}
        .jssora051 .a {fill:none;stroke:#fff;stroke-width:360;stroke-miterlimit:10;}
        .jssora051:hover {opacity:.8;}
        .jssora051.jssora051dn {opacity:.5;}
        .jssora051.jssora051ds {opacity:.3;pointer-events:none;}
    </style>
    <svg viewbox="0 0 0 0" width="0" height="0" style="display:block;position:relative;left:0px;top:0px;">
        <defs>
            <filter id="jssor_1_flt_1" x="-50%" y="-50%" width="200%" height="200%">
                <feGaussianBlur stddeviation="4"></feGaussianBlur>
            </filter>
            <radialGradient id="jssor_1_grd_2">
                <stop offset="0" stop-color="#fff"></stop>
                <stop offset="1" stop-color="#000"></stop>
            </radialGradient>
            <mask id="jssor_1_msk_3">
                <path fill="url(#jssor_1_grd_2)" d="M600,0L600,400L0,400L0,0Z" x="0" y="0" style="position:absolute;overflow:visible;"></path>
            </mask>
        </defs>
    </svg>
    <div id="jssor_1" style="position:relative;margin:0 auto;top:0px;left:0px;width:1600px;height:860px;overflow:hidden;visibility:hidden;">
        <!-- Loading Screen -->
        <div data-u="loading" class="jssorl-009-spin" style="position:absolute;top:0px;left:0px;width:100%;height:100%;text-align:center;background-color:rgba(0,0,0,0.7);">
            <img style="margin-top:-19px;position:relative;top:50%;width:38px;height:38px;" src="img/spin.svg" />
        </div>
        <div data-u="slides" style="cursor:default;position:relative;top:0px;left:0px;width:1600px;height:860px;overflow:hidden;">
            
            @foreach($photo as $home)
            
            <div style="background-color:#ffffff;">
                <img data-u="image" style="opacity:0.8;" data-src="img/{{$home->Photo}}" />
            
            </div>
            
            @endforeach
         
          
        
        </div><a data-scale="0" href="https://www.spingharkabul.edu.af" style="display:none;position:absolute;">slider html</a>
        <!-- Bullet Navigator -->
        <div data-u="navigator" class="jssorb132" style="position:absolute;bottom:24px;right:16px;" data-autocenter="1" data-scale="0.5" data-scale-bottom="0.75">
            <div data-u="prototype" class="i" style="width:12px;height:12px;">
                <svg viewbox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
                    <circle class="b" cx="8000" cy="8000" r="5800"></circle>
                </svg>
            </div>
        </div>
        <!-- Arrow Navigator -->
        <div data-u="arrowleft" class="jssora051" style="width:55px;height:55px;top:0px;left:25px;" data-autocenter="2" data-scale="0.75" data-scale-left="0.75">
            <svg viewbox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
                <polyline class="a" points="11040,1920 4960,8000 11040,14080 "></polyline>
            </svg>
        </div>
        <div data-u="arrowright" class="jssora051" style="width:55px;height:55px;top:0px;right:25px;" data-autocenter="2" data-scale="0.75" data-scale-right="0.75">
            <svg viewbox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
                <polyline class="a" points="4960,1920 11040,8000 4960,14080 "></polyline>
            </svg>
        </div>
    </div>
    <script type="text/javascript">jssor_1_slider_init();
    </script>
    <!-- #endregion Jssor Slider End -->


    <section class="u-clearfix u-white u-section-2" id="sec-378a">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h1 class="u-heading-font u-text u-text-default u-title u-text-1">
        @foreach($title as $heading) 
            {{$heading->Title}} 
        @endforeach</h1>


        <p class="u-text u-text-default u-text-2">


             @foreach($title as $heading) 


                 {!!$heading->Description!!}


               @endforeach

        </p>

      </div>



    </section>

<style>
.zoom{
  transition: transform .2s; /* Animation */
  margin: 0 auto;
}

.zoom:hover {
  transform: scale(1.5); /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
}
</style>


    <section class="u-align-center u-clearfix u-white u-section-3" id="sec-98bd">

<div style="height: 7px;" class="u-align-center u-container-style u-expanded-width u-group u-palette-1-base u-group-1" >
        <div class="u-container-layout u-container-layout-1">
          @foreach($pic10 as $heading) 
         <h4 class="u-text u-text-3"> {{$heading->BannerTitle}}</h4>
          @endforeach
        </div>
  </div>

  <div style="height: 190px; background-color: #28292A" class="u-align-center u-container-style u-expanded-width u-group u-palette-1-base u-group-1" >
         
         
             <table  style="width:100% !important;text-align: center;">
             <tr >
                 <td >
                    <a href="register" >
                    <font style="font-size: 60px;color:#ffffff;" class="zoom fa fa-file-text-o"></font> <br>
                    <font style="font-size: 25px;color:#ffffff;" >ADMISSION</font>
                  </a>
                 </td>
                 <td >
                <a href="" >
                    <font style="font-size: 60px;color:#ffffff;" class="zoom fa fa-graduation-cap"></font> <br>
                    <font style="font-size: 25px;color:#ffffff;" >Academics</font>
                </a>
                 </td>
                 <td >
                   <a href="" >
                    <font style="font-size: 60px;color:#ffffff;" class="zoom fa fa-search"></font> <br>
                    <font style="font-size: 25px;color:#ffffff;" >Research</font>
                    </a>
                 </td>
             </tr>
         </table>
         
  </div>

     




<div style="height: 70px;" class="u-align-center u-container-style u-expanded-width u-group u-palette-1-base u-group-1" data-animation-name="lightSpeedIn" data-animation-duration="1000" data-animation-delay="0" data-animation-direction="">
    
      
        <div class="u-container-layout">

          @foreach($pic10 as $heading) 
            <h4 class="u-text u-text-30"> {{$heading->BannerTitle1}}</h4>asdfasd
          @endforeach
          
        
        
        </div>
  </div>



    </section>



<section class="u-clearfix u-white u-section-2" id="sec-378a">
      <div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-text u-text-default u-text-2">
        </p>

          @foreach($news as $heading)

        <table style="vertical-align: top;left:20px;max-width: 900px;min-width: 200px;">
            
          

            <tr>
              <td rowspan="2">
            
         <a href="https://facebook.com/{{$heading->post_id}}" target="_blank" >
                  <!-- Click Here  -->
                 
              <img src="{{$heading->full_picture ?: './images/default_image.jpg'}}" style="
                border-radius: 10% !important;"  alt="" class="u-blog-control u-image u-image-default u-image-1 resImg" data-image-width="150" data-image-height="97">
               </a>

              </td>
              <td style="vertical-align: top;font-size: 26px;height: 50px;">
                
              
                 
              
              </td>
            </tr>
            <tr>
              <td style="vertical-align: top;" >
                <p dir="rtl">
                {{$heading->message}}
               </p>
                <br>
                Date Posted: <strong>
                    {{ date('Y-m-d', strtotime($heading->created_time)) }}
                </strong>
              </td>
            </tr>
          </table>
         <div style="height: 20px;"></div>
         <hr>
    
          @endforeach

 <div style="height: 100px;"></div>



      </div>

  

    </section>








    <section class="u-align-center u-clearfix u-white" id="sec-d249">

    <div style="height: 70px;" class="u-align-center u-container-style u-expanded-width u-group u-palette-1-base u-group-1" data-animation-name="lightSpeedIn" data-animation-duration="1000" data-animation-delay="0" data-animation-direction="">
    
      
        <div class="u-container-layout">
          
        

         @foreach($pic10 as $heading) 
         <h4 class="u-text u-text-3"> {{$heading->BannerTitle2}}</h4>
          @endforeach
        
        </div>
  </div>

    </section>


       <section class="u-align-left u-clearfix u-image u-shading u-section-7" id="sec-dd59" data-image-width="2250" data-image-height="1500">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
      
@foreach($pic11 as $heading) 
        <h2 class="u-text u-text-body-color u-text-default u-text-1">

        
{{$heading->Title}}


      </h2>
        <p class="u-text u-text-body-color u-text-2"> 
 {!!$heading->Description!!}
        </p>
 @endforeach

        <div class="u-list u-repeater u-list-1">
          
 @foreach($pic20 as $heading) 
          <div class="u-container-style u-list-item u-repeater-item u-white u-list-item-1">
            <div class="u-container-layout u-similar-container u-container-layout-1">
              <img alt="" class="u-expanded-width u-image u-image-default u-image-1" data-image-width="626" data-image-height="417" src="img/{{$heading->Photo}}">
              <h4 class="u-custom-font u-heading-font u-text u-text-palette-3-base u-text-3">
               
                   <a href="tech_details&{{$heading->ID}}" style="color: #f1c50e !important;" class="details" >
                   {{$heading->Title}}   
                 </a>
              </h4>
              <p class="u-text u-text-grey-50 u-text-4 show-read-more1">
                   {!!$heading->Description!!}
              </p>
            </div>
          </div>
 @endforeach

       
      
        </div>
    
      </div>
    </section>



    <section class="u-align-center u-clearfix u-white u-section-5" id="carousel_37d1">
      <h2 class="u-custom-font u-font-playfair-display u-text u-text-default u-text-1"> Spinghar University Kabul Campus Registered with:</h2>
     

<div class="u-clearfix u-sheet u-sheet-1">

 <!--start-->
    <div style="max-width:900px;margin-left: 10px;margin-top: -60px;padding:0px 0;">

        <div style="float:left;padding-top:98px;">
            <div id="thumbnail-slider">
                <div class="inner">
                    <ul>

                      @foreach($pic15 as $heading)
                       
                        <li>
                            <a class="thumb" href="images/{{$heading->Photo}}"></a>
                        </li>

                         @endforeach
                       
                    </ul>
                </div>
            </div>
        </div>


       

    </div>
    <!--end-->
</div>

    </section>




    
    <section class="u-clearfix u-grey-5 u-section-3-m" id="carousel_5d9b">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1-m">


<!-- Facebook page embeded -->
<!-- <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FKabul-Arya-Pharma-1888544151429023%2F&tabs=timeline&width=340&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId=1708011602768188" width="340" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe> -->




        <h2 class="u-text u-text-default u-text-1-m">
           @foreach($pic17 as $heading)
             {{$heading->footer_title}}
            @endforeach
        </h2>
        <div class="u-clearfix u-expanded-width u-gutter-0 u-layout-wrap-m u-layout-wrap-1-m">
          <div class="u-layout-m">
            <div class="u-layout-col">
              <div class="u-size-30">
                <div class="u-layout-row">
                  <div class="u-align-center u-container-style u-layout-cell u-left-cell u-size-15 u-size-30-md u-layout-cell-1-m">
                    <div class="u-container-layout u-container-layout-1"><span class="u-icon u-icon-circle u-text-grey-40 u-icon-1-m"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 512 512" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-fb01"></use></svg><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="svg-fb01" x="0px" y="0px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve" class="u-svg-content"><g><g><path d="M256,0C153.755,0,70.573,83.182,70.573,185.426c0,126.888,165.939,313.167,173.004,321.035    c6.636,7.391,18.222,7.378,24.846,0c7.065-7.868,173.004-194.147,173.004-321.035C441.425,83.182,358.244,0,256,0z M256,278.719    c-51.442,0-93.292-41.851-93.292-93.293S204.559,92.134,256,92.134s93.291,41.851,93.291,93.293S307.441,278.719,256,278.719z"></path>
</g>
</g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g></svg></span>
                      <h6 class="u-text u-text-default u-text-2-m">Location</h6>
                      <p class="u-text u-text-default u-text-3-m">
                           @foreach($pic17 as $heading)
                             {{$heading->Office}}
                            @endforeach
                      </p>
                    </div>
                  </div>
                  <div class="u-align-center-lg u-align-center-md u-align-center-sm u-align-center-xs u-container-style u-layout-cell u-size-15 u-size-30-md u-layout-cell-2-m">
                    <div class="u-container-layout u-valign-top-lg u-valign-top-xl u-container-layout-2-m"><span class="u-icon u-icon-circle u-text-grey-40 u-icon-2-m"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 384 384" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-cd86"></use></svg><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="svg-cd86" x="0px" y="0px" viewBox="0 0 384 384" style="enable-background:new 0 0 384 384;" xml:space="preserve" class="u-svg-content"><g><g><path d="M353.188,252.052c-23.51,0-46.594-3.677-68.469-10.906c-10.719-3.656-23.896-0.302-30.438,6.417l-43.177,32.594    c-50.073-26.729-80.917-57.563-107.281-107.26l31.635-42.052c8.219-8.208,11.167-20.198,7.635-31.448    c-7.26-21.99-10.948-45.063-10.948-68.583C132.146,13.823,118.323,0,101.333,0H30.813C13.823,0,0,13.823,0,30.813    C0,225.563,158.438,384,353.188,384c16.99,0,30.813-13.823,30.813-30.813v-70.323C384,265.875,370.177,252.052,353.188,252.052z"></path>
</g>
</g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g></svg></span>
                      <h6 class="u-align-center-xl u-text u-text-default u-text-4-m">phone number</h6>
                      <p class="u-align-center-xl u-text u-text-default u-text-5-m">
                          @foreach($pic17 as $heading)
                           {{$heading->Phone}}
                          @endforeach
                      </p>
                    </div>
                  </div>
                  <div class="u-align-center-md u-align-center-sm u-align-center-xs u-container-style u-layout-cell u-size-15 u-size-30-md u-layout-cell-3">
                    <div class="u-container-layout u-valign-top u-container-layout-3-m"><span class="u-icon u-icon-circle u-text-grey-40 u-icon-3-m"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 512 512" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-f872"></use></svg><svg xmlns="http://www.w3.org/2000/svg" id="svg-f872" enable-background="new 0 0 512 512" viewBox="0 0 512 512" class="u-svg-content"><path d="m201 12.714v184.286h267v-184.286c0-7.022-5.692-12.714-12.714-12.714h-241.572c-7.022 0-12.714 5.692-12.714 12.714zm63.89 33.131h70.271c8.284 0 15 6.716 15 15s-6.716 15-15 15h-70.271c-8.284 0-15-6.716-15-15s6.715-15 15-15zm0 75.142h139.22c8.284 0 15 6.716 15 15s-6.716 15-15 15h-139.22c-8.284 0-15-6.716-15-15s6.715-15 15-15z"></path><path d="m472 227h-275c-22.091 0-40 17.909-40 40v205c0 22.091 17.909 40 40 40h275c22.091 0 40-17.909 40-40v-205c0-22.091-17.909-40-40-40zm-207.5 217.5h-20c-8.284 0-15-6.716-15-15s6.716-15 15-15h20c8.284 0 15 6.716 15 15s-6.716 15-15 15zm0-60h-20c-8.284 0-15-6.716-15-15s6.716-15 15-15h20c8.284 0 15 6.716 15 15s-6.716 15-15 15zm0-60h-20c-8.284 0-15-6.716-15-15s6.716-15 15-15h20c8.284 0 15 6.716 15 15s-6.716 15-15 15zm80 120h-20c-8.284 0-15-6.716-15-15s6.716-15 15-15h20c8.284 0 15 6.716 15 15s-6.716 15-15 15zm0-60h-20c-8.284 0-15-6.716-15-15s6.716-15 15-15h20c8.284 0 15 6.716 15 15s-6.716 15-15 15zm0-60h-20c-8.284 0-15-6.716-15-15s6.716-15 15-15h20c8.284 0 15 6.716 15 15s-6.716 15-15 15zm80 120h-20c-8.284 0-15-6.716-15-15s6.716-15 15-15h20c8.284 0 15 6.716 15 15s-6.716 15-15 15zm0-60h-20c-8.284 0-15-6.716-15-15s6.716-15 15-15h20c8.284 0 15 6.716 15 15s-6.716 15-15 15zm0-60h-20c-8.284 0-15-6.716-15-15s6.716-15 15-15h20c8.284 0 15 6.716 15 15s-6.716 15-15 15z"></path><path d="m87 227h-47c-22.091 0-40 17.909-40 40v205c0 22.091 17.909 40 40 40h47c22.091 0 40-17.909 40-40v-205c0-22.091-17.909-40-40-40z"></path></svg></span>
                      <h6 class="u-align-center-lg u-align-center-xl u-text u-text-default u-text-6-m">fax</h6>
                      <p class="u-align-center-lg u-align-center-xl u-text u-text-default u-text-7-m">
                         @foreach($pic17 as $heading)
                           {{$heading->Fax}}
                          @endforeach
                      </p>
                    </div>
                  </div>
                  <div class="u-align-center-lg u-align-center-md u-align-center-sm u-align-center-xs u-container-style u-layout-cell u-right-cell u-size-15 u-size-30-md u-layout-cell-4">
                    <div class="u-container-layout u-valign-top u-container-layout-4-m"><span class="u-icon u-icon-circle u-text-grey-40 u-icon-4-m"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 512 512" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-d2c4"></use></svg><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="svg-d2c4" x="0px" y="0px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve" class="u-svg-content"><g><g><path d="M467,61H45c-6.927,0-13.412,1.703-19.279,4.51L255,294.789l51.389-49.387c0,0,0.004-0.005,0.005-0.007    c0.001-0.002,0.005-0.004,0.005-0.004L486.286,65.514C480.418,62.705,473.929,61,467,61z"></path>
</g>
</g><g><g><path d="M507.496,86.728L338.213,256.002L507.49,425.279c2.807-5.867,4.51-12.352,4.51-19.279V106    C512,99.077,510.301,92.593,507.496,86.728z"></path>
</g>
</g><g><g><path d="M4.51,86.721C1.703,92.588,0,99.073,0,106v300c0,6.923,1.701,13.409,4.506,19.274L173.789,256L4.51,86.721z"></path>
</g>
</g><g><g><path d="M317.002,277.213l-51.396,49.393c-2.93,2.93-6.768,4.395-10.605,4.395s-7.676-1.465-10.605-4.395L195,277.211    L25.714,446.486C31.582,449.295,38.071,451,45,451h422c6.927,0,13.412-1.703,19.279-4.51L317.002,277.213z"></path>
</g>
</g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g></svg></span>
                      <h6 class="u-align-center-xl u-text u-text-default u-text-8-m">mail</h6>
                      <p class="u-align-center-xl u-text u-text-default u-text-9-m">
                         @foreach($pic17 as $heading)
                           {{$heading->Mail}}
                          @endforeach
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="u-size-30">
                <div class="u-layout-col">
                  <div class="u-container-style u-layout-cell u-right-cell u-size-60 u-layout-cell-5-m">
                    <div class="u-container-layout u-container-layout-5">
                      <div class="u-expanded u-grey-light-2 u-map">
                        <div class="embed-responsive">
                          <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13151.762643988914!2d69.215908!3d34.5043886!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x26f983aaa2305bae!2sSpinghar%20Medical%20University!5e0!3m2!1sen!2s!4v1662455199419!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    

@endsection





    
