<?php 


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/v15.0/922127214530498?fields=posts%7Bfull_picture%2Cmessage%2Ccreated_time%7D%2Cname%2Cpicture&access_token=EAAJIwCcdItMBAJk7eCuJ7IMUSvwN2jAEYSh7bqOpI3jm1Cw56CcDxEDHKZCLIKZADNaLZCNc17TZBmFhd9RuwMjwXqZBCUmJb2vZAe0M6bl8LBhcRXjEkyBpxHr5szlDqg8xqvukIyx8uVPdrnHwY3MXwOkwgCBWR6DInDfMI53ket3IrNYAtxxmZBd2O2fpZAWDfdCKbVZAevr3dwJDsc5pv');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);





$result = json_decode($result);

echo '<pre>';
print_r($result);

?>