<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OnlineRegister extends Model
{
    use HasFactory;

    // public $timestamps = false;

    protected $fillable = [
    'studentName',
    'studentNameLetter1',
    'studentNameLetter2',
    'studentNameLetter3',
    'studentNameLetter4',
    'studentNameLetter5',
    'studentNameLetter6',
    'studentNameLetter7',
    'studentNameLetter8',
    'studentNameLetter9',
    'studentNameLetter10',
    'studentNameLetter11',
    'studentNameLetter12',
    'studentNameLetter13',
    'studentNameLetter14',
    'studentNameLetter15',
    'studentFatherName',
    'studentFatherNameLetter1',
    'studentFatherNameLetter2',
    'studentFatherNameLetter3',
    'studentFatherNameLetter4',
    'studentFatherNameLetter5',
    'studentFatherNameLetter6',
    'studentFatherNameLetter7',
    'studentFatherNameLetter8',
    'studentFatherNameLetter9',
    'studentFatherNameLetter10',
    'studentFatherNameLetter11',
    'studentFatherNameLetter12',
    'studentFatherNameLetter13',
    'studentFatherNameLetter14',
    'studentFatherNameLetter15',
    'studentLastName',
    'studentLastNameLetter1',
    'studentLastNameLetter2',
    'studentLastNameLetter3',
    'studentLastNameLetter4',
    'studentLastNameLetter5',
    'studentLastNameLetter6',
    'studentLastNameLetter7',
    'studentLastNameLetter8',
    'studentLastNameLetter9',
    'studentLastNameLetter10',
    'studentLastNameLetter11',
    'studentLastNameLetter12',
    'studentLastNameLetter13',
    'studentLastNameLetter14',
    'studentLastNameLetter15',
    'studentGrandFatherName',
    'studentGrandFatherNameLetter1',
    'studentGrandFatherNameLetter2',
    'studentGrandFatherNameLetter3',
    'studentGrandFatherNameLetter4',
    'studentGrandFatherNameLetter5',
    'studentGrandFatherNameLetter6',
    'studentGrandFatherNameLetter7',
    'studentGrandFatherNameLetter8',
    'studentGrandFatherNameLetter9',
    'studentGrandFatherNameLetter10',
    'studentGrandFatherNameLetter11',
    'studentGrandFatherNameLetter12',
    'studentGrandFatherNameLetter13',
    'studentGrandFatherNameLetter14',
    'studentGrandFatherNameLetter15',
    'DoB',
    'studentGender',
    'examLang',
    'examType',
    'relativeName',
    'relativeType',
    'relativeJob',
    'relativePhone',
    'studentProvince',
    'studentDistrict',
    'studentVillage',
    'studentTazkiraNo',
    'studentPassport',
    'studentSchool',
    'schoolGraduateYear',
    'studentPhone',
    'studentEmail',
    'faculty',
    'certificate',
    'certificate1',
    'certificate2',
    'certificate3',
    'certificate4'
];
}
